/**
 * Calendar export utilities: ICS (RFC 5545) and PDF.
 *
 * PDF requires jspdf + jspdf-autotable:
 *   npm install jspdf jspdf-autotable --legacy-peer-deps
 */

// ─── ICS Export ──────────────────────────────────────────────────────────────

function pad(n) {
  return String(n).padStart(2, '0');
}

/** Format a Date as a local YYYYMMDDTHHMMSS string (no timezone suffix). */
function icsLocalDateTime(date) {
  return (
    `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}` +
    `T${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`
  );
}

function escapeIcs(str) {
  return String(str ?? '').replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');
}

/**
 * Build RFC 5545 .ics string from a weeklySchedule + weekId (YYYY-MM-DD monday).
 */
export function buildIcsString(schedule, weekId) {
  const dayOffsets = { Monday: 0, Tuesday: 1, Wednesday: 2, Thursday: 3, Friday: 4, Saturday: 5, Sunday: 6 };
  const [yr, mo, dy] = weekId.split('-').map(Number);
  const monday = new Date(yr, mo - 1, dy);

  const vevents = schedule.papers
    .filter((p) => p.scheduledDay && p.scheduledStart)
    .map((p) => {
      const dayOffset = dayOffsets[p.scheduledDay] ?? 0;
      const [startH, startM] = p.scheduledStart.split(':').map(Number);
      const startDate = new Date(monday);
      startDate.setDate(startDate.getDate() + dayOffset);
      startDate.setHours(startH, startM, 0, 0);

      const endDate = new Date(startDate);
      endDate.setMinutes(endDate.getMinutes() + (p.duration ?? 90));

      const uid = `${weekId}-${p.subject}-${p.paperPath ?? p.displayName}-${startH}${startM}@alevplanner`;

      const descParts = [`Subject: ${p.subject}`, `Path: ${p.paperPath ?? ''}`];
      if (p.completed) {
        descParts.push(`Grade: ${p.grade ?? '—'} | Marks: ${p.marks ?? '—'}`);
      }

      return [
        'BEGIN:VEVENT',
        `UID:${uid}`,
        `DTSTART:${icsLocalDateTime(startDate)}`,
        `DTEND:${icsLocalDateTime(endDate)}`,
        `SUMMARY:${escapeIcs(`${p.displayName}`)}`,
        `DESCRIPTION:${escapeIcs(descParts.join('\\n'))}`,
        'END:VEVENT',
      ].join('\r\n');
    });

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//A-Level Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    ...vevents,
    'END:VCALENDAR',
  ];
  return lines.join('\r\n');
}

/** Trigger a browser download of the .ics file. */
export function downloadIcs(schedule, weekId) {
  const content = buildIcsString(schedule, weekId);
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `week-${weekId}.ics`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── PDF Export ───────────────────────────────────────────────────────────────

/**
 * Generate and download a PDF table of the week schedule.
 * Requires jspdf + jspdf-autotable installed.
 */
export async function downloadPdf(schedule, weekId) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text(`Study Schedule — Week of ${weekId}`, 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by A-Level Planner`, 14, 26);

  const DAYS_ORDER = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  const rows = [...schedule.papers]
    .sort((a, b) => {
      const di = DAYS_ORDER.indexOf(a.scheduledDay) - DAYS_ORDER.indexOf(b.scheduledDay);
      return di !== 0 ? di : (a.scheduledStart ?? '').localeCompare(b.scheduledStart ?? '');
    })
    .map((p) => [
      p.scheduledDay ?? '—',
      p.scheduledStart ? `${p.scheduledStart}–${p.scheduledEnd}` : '—',
      p.subject,
      p.displayName,
      `${p.duration ?? 90} min`,
      p.completed ? (p.grade ?? '—') : '—',
      p.completed ? (p.marks ?? '—') : '—',
    ]);

  autoTable(doc, {
    startY: 32,
    head: [['Day', 'Time', 'Subject', 'Paper', 'Duration', 'Grade', 'Marks']],
    body: rows,
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 26 },
      2: { cellWidth: 24 },
      4: { cellWidth: 18 },
      5: { cellWidth: 14 },
      6: { cellWidth: 18 },
    },
  });

  doc.save(`week-${weekId}-schedule.pdf`);
}
