export const TUTORIAL_STEPS = [
  {
    key: 'WELCOME',
    route: '/dashboard',
    targetId: null,
    title: 'Welcome to your study planner!',
    body: "Let's take a quick tour (≈2 min) to set up your first week of revision. You can skip at any time.",
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'TERM_SCHEDULE_INTRO',
    route: '/term-schedule',
    targetId: 'term-schedule-grid',
    title: 'Step 1 — Term Schedule',
    body: "This is your term calendar. You paint each week as Week A, Week B, or Holiday so the generator knows when you're studying.",
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'TERM_SCHEDULE_PAINT_CONTROLS',
    route: '/term-schedule',
    targetId: 'term-schedule-paint-controls',
    title: 'Choose a week type',
    body: 'Select "Week A" or "Week B" here, then click a week in the grid to paint it. Holiday weeks will be skipped during generation.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'TERM_SCHEDULE_PAINT',
    route: '/term-schedule',
    targetId: 'term-schedule-grid',
    title: 'Paint a week',
    body: "Go ahead — click any week in the grid to paint it. The \"Next\" button will activate once you've painted at least one week.",
    requiresAction: true,
    isFinal: false,
  },
  {
    key: 'TEMPLATES_INTRO',
    route: '/templates',
    targetId: 'templates-list',
    title: 'Step 2 — Week Templates',
    body: 'Templates define your study time blocks for each week type. You already have Week A and Week B templates created from onboarding.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'TEMPLATES_EDIT',
    route: '/templates',
    targetId: 'template-card-week-a',
    title: 'Edit your Week A template',
    body: 'Click "Edit" on this card to customise your time blocks, max papers per subject, and other settings. You can come back any time.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'GENERATE_INTRO',
    route: '/generate',
    targetId: 'generate-page-root',
    title: 'Step 3 — Generate a Schedule',
    body: "The generator picks past papers for each session based on your templates and what you've already completed.",
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'GENERATE_WEEK',
    route: '/generate',
    targetId: 'generate-week-picker',
    title: 'Pick a week',
    body: 'Choose the Monday of the week you want to generate. It will snap to the correct Monday automatically.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'GENERATE_PREVIEW',
    route: '/generate',
    targetId: 'generate-generate-btn',
    title: 'Generate the schedule',
    body: 'Click "Generate Schedule" to preview the papers chosen for your week. You can regenerate as many times as you like.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'GENERATE_SAVE',
    route: '/generate',
    targetId: 'generate-save-btn',
    title: 'Save the schedule',
    body: "Happy with the preview? Hit \"Save Schedule\" to lock it in. The \"Next\" button activates once it's saved.",
    requiresAction: true,
    isFinal: false,
  },
  {
    key: 'CALENDAR_INTRO',
    route: '/calendar',
    targetId: 'calendar-grid',
    title: 'Step 4 — Your Calendar',
    body: 'Your saved papers appear here as coloured blocks. Drag them to reschedule, or click to mark them complete.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'CALENDAR_COMPLETE',
    route: '/calendar',
    targetId: 'calendar-first-paper',
    title: 'Mark a paper complete',
    body: 'Click any paper block to record your marks and grade. Progress is tracked in your Dashboard and History.',
    requiresAction: false,
    isFinal: false,
  },
  {
    key: 'DONE',
    route: null,
    targetId: null,
    title: "You're all set!",
    body: "You know the core workflow now. Repeat the Term Schedule → Generate → Calendar loop each week. Good luck with your revision!",
    requiresAction: false,
    isFinal: true,
  },
];
